paths:
  pdf_dir: "./corpus/pdfs"
  index_dir: "./vector_store"

embedding:
  model_name: "BAAI/bge-small-en-v1.5"
  device: "cpu"

chunking:
  chunk_size: 1000
  chunk_overlap: 150

llm:
  hf_model: "TinyLlama/TinyLlama-1.1B-Chat-v1.0"
  temperature: 0.2
  max_new_tokens: 300
